```{r create_list}
library(readr)
mtcars <- read_csv("mtcars.csv")

# Vector with numerics from 1 up to 10
my_vector <- 1:10

# Matrix with numerics from 1 up to 9
my_matrix <- matrix(1:9, ncol = 3)

# First 10 elements of the built-in data frame mtcars
my_df <- mtcars[1:10, ]

# Construct list with these different elements:
my_list <- list(my_vector, my_matrix, my_df)

# Adapt list() call to give the components names
names(my_list) <- c("vec", "mat", "df")
```
```{r create_named_list}
mov <- c("The Shining")
act <- c("Jack Nicholson", "Shelley Duvall", "Danny Lloyd", "Scatman Crothers", "Barry Nelson")
rev <- read_csv("rev.csv")
shining_list <- list(moviename = mov, actors = act, reviews = rev)
# Print out the vector representing the actors (same as shinin_list[["actors"]])
shining_list$actors

# Print the second element of the vector representing the actors
shining_list$actors[2]
```
```{r list_excersise}
movie_title <- c("The Departed")
movie_actors <- c("Leonardo DiCaprio", "Matt Damon", "Jack Nicholson", "Mark Wahlberg", "Vera Farmiga", "Martin Sheen")
scores <- c(4.6, 5, 4.8, 5, 4.2)
comments <- c("I would watch it again", "Amazing!", "I liked it", "One of the best movies", "Fascinating plot")

# Save the average of the scores vector as avg_review
avg_review <- mean(scores)

# Combine scores and comments into the reviews_df data frame
reviews_df <- data.frame(scores, comments)

# Create and print out a list, called departed_list
departed_list <- list(movie_title, movie_actors, reviews_df, avg_review)
departed_list
```