World Happiness Report 
https://worldhappiness.report/ed/2019/

```{r worldhappiness}
library(readr)
library(dplyr)
library(ggplot2)
world_happiness <- read_csv("world_happiness.csv")
```
```{r corr_visual}
# Create a scatterplot of happiness_score vs. life_exp
# Add a linear trendline to scatterplot
ggplot(world_happiness, aes(x = life_exp, y = happiness_score)) + 
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)

# Correlation between life_exp and happiness_score
cor(world_happiness$happiness_score, world_happiness$life_exp)
```
```{r corr_transforming_var}
# Scatterplot of gdp_per_cap and life_exp
ggplot(world_happiness, aes(x = gdp_per_cap, y = life_exp)) + geom_point()

# Correlation between gdp_per_cap and life_exp
cor(world_happiness$life_exp, world_happiness$gdp_per_cap)

# Scatterplot of happiness_score vs. gdp_per_cap
ggplot(world_happiness, aes(x = gdp_per_cap, y = happiness_score)) + geom_point()

# Calculate correlation
cor(world_happiness$gdp_per_cap, world_happiness$happiness_score)

# Create log_gdp_per_cap column
world_happiness <- world_happiness %>%
  mutate(log_gdp_per_cap = log(gdp_per_cap))

# Scatterplot of happiness_score vs. log_gdp_per_cap
ggplot(world_happiness, aes(x = log_gdp_per_cap, y = happiness_score)) +
  geom_point()

# Calculate correlation
cor(world_happiness$log_gdp_per_cap, world_happiness$happiness_score)
```