```{r for_loop_vector}
# The linkedin vector has already been defined for you
linkedin <- c(16, 9, 13, 5, 2, 17, 14)

# Loop version 1
for (views in linkedin) {
  print(views)
}



# Loop version 2
for (i in 1:length(linkedin)) {
  print(linkedin[i])
}
```
```{r for_loop_list}
# The nyc list is already specified
nyc <- list(pop = 8405837,
            boroughs = c("Manhattan", "Bronx", "Brooklyn", "Queens", "Staten Island"), 
            capital = FALSE)

# Loop version 1
for (el in nyc) {
  print(el)
}



# Loop version 2
for (i in 1:length(nyc)) {
  print(nyc[[i]])
}
```
```{r for_loop_matrix}
t <- c("O", NA, "X", NA, "O", "O", "X", NA, "X")
ttt <- matrix(t, byrow = TRUE, nrow = 3)
# define the double for loop
for (i in 1:nrow(ttt)) {
  for (j in 1:ncol(ttt)) {
    print(paste("On row", i, " and column", j, " the board contains ", ttt[i, j]))
  }
}
```
```{r for_loop_flow_control}
# The linkedin vector has already been defined for you
linkedin <- c(16, 9, 13, 5, 2, 17, 14)

# Code the for loop with conditionals
for (li in linkedin) {
  if (li > 10) {
    print("You're popular!")
  } else {
    print("Be more visible!")
  }
  print(li)
}
```
```{r for_loop_next_break}
# The linkedin vector has already been defined for you
linkedin <- c(16, 9, 13, 5, 2, 17, 14)

# Adapt/extend the for loop
for (li in linkedin) {
  if (li > 10) {
    print("You're popular!")
  } else {
    print("Be more visible!")
  }

  # Add if statement with break
  if (li > 16) {
    print("This is ridiculous, I'm outta here!")
    break
  }

  # Add if statement with next
  if (li < 5) {
    print("This is too embarrassing!")
    next
  }

  print(li)
}
```
```{r for_loop_exercise}
# Pre-defined variables
rquote <- "r's internals are irrefutably intriguing"
chars <- strsplit(rquote, split = "")[[1]]

# Initialize rcount
rcount <- 0

# Finish the for loop
for (char in chars) {
  if (char == "r") {
    rcount <- rcount + 1
  }
  if (char == "u") {
    break
  }
}

# Print out rcount
rcount
```